#!/bin/sh

. _LIBRARY_PATH_/_APPLICATION_NAME_/setup/include.sh

_console_install

# run for current user
_HOME=$HOME
_zsh_conf

# setup windows 10 notifications
cp .files/notifications.ps1 $_HOME/.config/walterjwhite/console-notifications.ps1
