#!/bin/sh

. _APPLICATION_CONFIG_PATH_
. _CONFIG_PATH_/install

if [ -z "$_SH_RC_PATH" ]; then
	exitWithError "_SH_RC_PATH is null, it must be set, recommend: /usr/local/walterjwhite/shrc, custom settings will be installed here"
fi

_ZSH_RC_PATH=$_SH_RC_PATH/zshrc

# copy over settings
mkdir -p $_ZSH_RC_PATH
if [ -e .zshrc ]; then
	cp .zshrc/* $_ZSH_RC_PATH
fi

_zsh_conf() {
	cp .files/.zshrc .files/.zlogout $_HOME
	cp .files/notifications.ps1 $_HOME/.config/walterjwhite/console-notifications.ps1

	if [ -n "$_OTHER_USER" ]; then
		chown $_OTHER_USER:$_OTHER_USER $_HOME/.zshrc $_HOME/.zlogout
	fi

	$_GNU_SED -i "1 a _ZSH_RC_PATH=$_ZSH_RC_PATH" $_HOME/.zshrc
}

# run for current user
_HOME=$HOME
_zsh_conf
