#!/bin/sh

if [[ $- != *i* ]]; then
	# Shell is non-interactive.
	exit
fi

. ~/.config/walterjwhite/console

_log() {
	local _message="### $1 - $(date "+%Y/%m/%d %H:%M:%S %Z") ###"
	echo -e "\e[1;3;34m$_message\e[0m ${3}"
}

before_command() {
	_log After

	_current_time
	if [ -n "$_CURRENT_TIME" ] && [ -n "$_TIMEOUT" ]; then
		if [ $_CURRENT_TIME -gt $_TIMEOUT ]; then
			_after
		fi
	fi
}

before_prompt() {
	_log Before

	_timeout
}

autoload -U add-zsh-hook
add-zsh-hook precmd before_command
add-zsh-hook preexec before_prompt

echo >&2 -e "$(date "+$_DATE_FORMAT") \e[35m$1\e[0m"
